// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafeSphere.API.Data;

#nullable disable

namespace SafeSphere.API.Migrations
{
    [DbContext(typeof(SafeSphereDbContext))]
    [Migration("20251027020240_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeSphere.API.Models.PanicAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("LocationLat")
                        .HasColumnType("double precision");

                    b.Property<double>("LocationLng")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PanicAlerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalInfo = "False alarm",
                            LocationLat = 40.712800000000001,
                            LocationLng = -74.006,
                            Status = "Resolved",
                            Timestamp = new DateTime(2025, 10, 27, 0, 2, 40, 338, DateTimeKind.Utc).AddTicks(4252),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdditionalInfo = "Need help",
                            LocationLat = 34.052199999999999,
                            LocationLng = -118.2437,
                            Status = "Active",
                            Timestamp = new DateTime(2025, 10, 27, 1, 32, 40, 338, DateTimeKind.Utc).AddTicks(4266),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SafeSphere.API.Models.SOSAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acknowledged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("LocationLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocationLng")
                        .HasColumnType("double precision");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SOSAlerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acknowledged = true,
                            AcknowledgedAt = new DateTime(2025, 10, 27, 1, 17, 40, 338, DateTimeKind.Utc).AddTicks(4338),
                            Location = "Highway 101, San Francisco",
                            LocationLat = 37.774900000000002,
                            LocationLng = -122.4194,
                            Message = "Car accident on Highway 101",
                            Timestamp = new DateTime(2025, 10, 27, 1, 2, 40, 338, DateTimeKind.Utc).AddTicks(4336),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Acknowledged = false,
                            Location = "Downtown, Los Angeles",
                            LocationLat = 34.052199999999999,
                            LocationLng = -118.2437,
                            Message = "Feeling unsafe, please check on me",
                            Timestamp = new DateTime(2025, 10, 27, 1, 47, 40, 338, DateTimeKind.Utc).AddTicks(4346),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SafeSphere.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmergencyContacts")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 27, 2, 2, 40, 197, DateTimeKind.Utc).AddTicks(5560),
                            Email = "john.doe@example.com",
                            EmergencyContacts = "Jane Doe:+1234567891,Police:911",
                            Name = "John Doe",
                            PasswordHash = "$2a$11$l14925j.HCIw03SM1wwveu5xN4c7WAxEO1cV/rxjEQIFM0v/aHGnS",
                            Phone = "+1234567890"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 27, 2, 2, 40, 338, DateTimeKind.Utc).AddTicks(3283),
                            Email = "jane.smith@example.com",
                            EmergencyContacts = "John Smith:+1234567893,Emergency:911",
                            Name = "Jane Smith",
                            PasswordHash = "$2a$11$pe1sIZnu.vBBFo.YKBQOl.nyUseos.FK3e8V6e9on1Dib/PHr3Yu.",
                            Phone = "+1234567892"
                        });
                });

            modelBuilder.Entity("SafeSphere.API.Models.PanicAlert", b =>
                {
                    b.HasOne("SafeSphere.API.Models.User", "User")
                        .WithMany("PanicAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeSphere.API.Models.SOSAlert", b =>
                {
                    b.HasOne("SafeSphere.API.Models.User", "User")
                        .WithMany("SOSAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeSphere.API.Models.User", b =>
                {
                    b.Navigation("PanicAlerts");

                    b.Navigation("SOSAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
